### ISSUE TITLE
Implement GUI and integrate Eight queens puzzle algorithm

### ISSUE THREAD

**Issue by chaaals** [chaaals/is-eight-queens#8]
## Description
Create a GUI and integrate the Eight queens puzzle algorithm. The interface must be able to show an 8x8 board, allow users to place and remove queens, switch modes, and reset modes.

## ⚙️ Implementation Details
We'll use the Tkinter library for our GUI.

#### Tasks
- [x] Create a simple UI design using Figma
- [x] Gather relevant assets such as valid & invalid queen, kill zones, reset asset, and switch asset
- [ ] Add background music
- [x] Implement UI design using Tkinter
